[package]
name = "boxxy"
version = "0.7.1"
edition = "2021"
repository = "https://github.com/queer/boxxy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
bat = { version = "0.23.0", default-features = false, features = ["atty", "regex-onig"] }
byteorder = "1.4.3"
cfg-if = "1.0.0"
clap = { version = "4.1.11", features = ["derive"] }
color-eyre = { version = "0.6.2", features = ["issue-url"] }
config = "0.13.3"
ctrlc = "3.2.5"
dirs = "5.0.1"
dotenv = "0.15.0"
dotenv-parser = "0.1.3"
haikunator = "0.1.2"
lazy_static = "1.4.0"
libc = "0.2.144"
log = "0.4.17"
nix = "0.26.2"
owo-colors = { version = "3.5.0", features = ["supports-color", "supports-colors"] }
pretty_env_logger = "0.5.0"
regex = "1.8.1"
rlimit = "0.9.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
shellexpand = "3.1.0"
strum = { version = "0.24.1", features = ["derive"] }
syscall-numbers = "3.1.0"
which = "4.4.0"

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"
