name: "Run cargo audit"
on:
  push:
    branches:
    - "mistress"
    paths:
    - "**.rs"
    - "**.toml"
  pull_request:
    branches:
    - "mistress"
    paths:
    - "**.rs"
    - "**.toml"

jobs:
  run-cargo-audit:
    strategy:
      matrix:
        version: ["stable", "1.67"]
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Install latest stable Rust"
      uses: "actions-rs/toolchain@v1"
      with:
        toolchain: "${{ matrix.version }}"
        override: true
    - name: "Install cargo-audit"
      run: "cargo install cargo-audit"
    - uses: "Swatinem/rust-cache@v1"
      with:
        key: "cargo-audit"
    - name: "Run cargo-audit"
      run: "cargo audit -q"
