name: "Run clippy lints"
on:
  push:
    branches:
    - "mistress"
    paths:
    - "**.rs"
  pull_request:
    branches:
    - "mistress"
    paths:
    - "**.rs"

jobs:
  run-clippy:
    strategy:
      matrix:
        version: ["stable", "1.67"]
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Install latest stable Rust"
      uses: "actions-rs/toolchain@v1"
      with:
        toolchain: "${{ matrix.version }}"
        override: true
        components: "clippy"
    - uses: "Swatinem/rust-cache@v1"
      with:
        key: "clippy"
    - name: "Run clippy"
      run: "cargo clippy --all-targets --all-features -- -D warnings"
