name: "Run all tests"
on:
  push:
    branches:
    - "mistress"
    paths:
    - "**.rs"
  pull_request:
    branches:
    - "mistress"
    paths:
    - "**.rs"

jobs:
  run-tests:
    strategy:
      matrix:
        version: ["stable", "nightly", "1.67"]
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Install latest stable Rust"
      uses: "actions-rs/toolchain@v1"
      with:
        toolchain: "${{ matrix.version }}"
        override: true
    - uses: "Swatinem/rust-cache@v1"
      with:
        key: "tests"
    - name: "Run tests"
      run: "cargo test"
